# Generated by Django 3.1.5 on 2021-01-07 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Confirmpassword',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Phonenumber',
        ),
        migrations.AddField(
            model_name='student',
            name='number',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
