# Generated by Django 3.1.5 on 2021-01-07 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0002_auto_20210107_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='number',
        ),
        migrations.AddField(
            model_name='student',
            name='Confirmpassword',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Dateofbirth',
            field=models.DateField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Password',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Phonenumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
