# Generated by Django 3.1.5 on 2021-01-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0003_auto_20210107_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='confirm_password',
            new_name='Confirmpassword',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='phonenumber',
            new_name='Univcontactnumber',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='institute_email',
            new_name='Universitymail',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='universityname',
            new_name='Universityname',
        ),
        migrations.RemoveField(
            model_name='university',
            name='personal_email',
        ),
    ]
