# Generated by Django 3.1.5 on 2021-01-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0005_stdquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stddetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=500)),
                ('Lastname', models.CharField(max_length=500)),
                ('Dateofbirth', models.DateField(max_length=50)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=50)),
                ('Maritial', models.CharField(choices=[('S', 'Single'), ('F', 'Female')], max_length=50)),
                ('Nationality', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('Phonenumber', models.CharField(max_length=50)),
                ('Sscqual', models.CharField(max_length=50)),
                ('Sscname', models.CharField(max_length=50)),
                ('Sscdate', models.DateField(max_length=10)),
                ('Sscmarks', models.CharField(max_length=10)),
                ('Sscgrading', models.CharField(choices=[('M', 'Marks'), ('%', 'Percentage'), ('C', 'CGPA')], max_length=50)),
                ('SscDoc', models.FileField(upload_to='')),
                ('Intqual', models.CharField(max_length=50)),
                ('Intname', models.CharField(max_length=50)),
                ('Intdate', models.DateField(max_length=10)),
                ('Intmarks', models.CharField(max_length=10)),
                ('Intgrading', models.CharField(choices=[('M', 'Marks'), ('%', 'Percentage'), ('C', 'CGPA')], max_length=50)),
                ('IntDoc', models.FileField(upload_to='')),
                ('Uniqual', models.CharField(max_length=50)),
                ('Uniname', models.CharField(max_length=50)),
                ('Unicname', models.CharField(max_length=50)),
                ('Unidate', models.DateField(max_length=10)),
                ('Unimarks', models.CharField(max_length=10)),
                ('Unigrading', models.CharField(choices=[('M', 'Marks'), ('%', 'Percentage'), ('C', 'CGPA')], max_length=50)),
                ('UniDoc', models.FileField(upload_to='')),
                ('Testeng', models.CharField(choices=[('I', 'IELTS'), ('T', 'TOEFL'), ('O', 'OTHERS')], max_length=50)),
                ('Yeareng', models.CharField(max_length=10)),
                ('Overallscoreeng', models.CharField(max_length=10)),
                ('Uploadeng', models.FileField(upload_to='')),
                ('Testeng1', models.CharField(choices=[('I', 'IELTS'), ('T', 'TOEFL'), ('O', 'OTHERS')], max_length=50)),
                ('Yeareng1', models.CharField(max_length=10)),
                ('Overallscoreeng1', models.CharField(max_length=10)),
                ('Uploadeng1', models.FileField(upload_to='')),
                ('Testad', models.CharField(choices=[('G', 'GMAT'), ('O', 'OTHERS')], max_length=50)),
                ('Yearad', models.CharField(max_length=10)),
                ('Overallscoread', models.CharField(max_length=10)),
                ('Uploadad', models.FileField(upload_to='')),
                ('Testad1', models.CharField(choices=[('G', 'GMAT'), ('O', 'OTHERS')], max_length=50)),
                ('Yearad1', models.CharField(max_length=10)),
                ('Overallscoread1', models.CharField(max_length=10)),
                ('Uploadad1', models.FileField(upload_to='')),
                ('Applyingfor', models.CharField(choices=[('B', 'Bachelors'), ('M', 'Masters')], max_length=50)),
                ('Date', models.DateField(max_length=50)),
                ('pcoun1', models.CharField(max_length=50)),
                ('pcoun2', models.CharField(max_length=50)),
                ('pcoun3', models.CharField(max_length=50)),
                ('pcour4', models.CharField(max_length=50)),
                ('pcour5', models.CharField(max_length=50)),
                ('pcour6', models.CharField(max_length=50)),
            ],
        ),
    ]
