# Generated by Django 3.1.5 on 2021-01-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0006_stddetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stddetail',
            name='UniDoc',
            field=models.FileField(upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Uploadad',
            field=models.FileField(upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Uploadad1',
            field=models.FileField(upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Uploadeng',
            field=models.FileField(upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Uploadeng1',
            field=models.FileField(upload_to='docs/'),
        ),
    ]
