# Generated by Django 3.1.5 on 2021-01-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0007_auto_20210109_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stddetail',
            name='IntDoc',
            field=models.FileField(upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='SscDoc',
            field=models.FileField(upload_to='docs/'),
        ),
    ]
