# Generated by Django 3.1.5 on 2021-01-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0008_auto_20210109_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stddetail',
            name='Applyingfor',
            field=models.CharField(choices=[('B', 'Bachelors'), ('M', 'Masters')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Intgrading',
            field=models.CharField(choices=[('M', 'Marks'), ('%', 'Percentage'), ('C', 'CGPA')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Sscgrading',
            field=models.CharField(choices=[('M', 'Marks'), ('%', 'Percentage'), ('C', 'CGPA')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Testad',
            field=models.CharField(choices=[('G', 'GMAT'), ('O', 'OTHERS')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Testad1',
            field=models.CharField(choices=[('G', 'GMAT'), ('O', 'OTHERS')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Testeng',
            field=models.CharField(choices=[('I', 'IELTS'), ('T', 'TOEFL'), ('O', 'OTHERS')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Testeng1',
            field=models.CharField(choices=[('I', 'IELTS'), ('T', 'TOEFL'), ('O', 'OTHERS')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Unigrading',
            field=models.CharField(choices=[('M', 'Marks'), ('%', 'Percentage'), ('C', 'CGPA')], max_length=50, null=True),
        ),
    ]
