# Generated by Django 3.1.5 on 2021-01-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0009_auto_20210109_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stddetail',
            name='Dateofbirth',
            field=models.DateField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Intdate',
            field=models.DateField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Maritial',
            field=models.CharField(choices=[('S', 'Single'), ('F', 'Female')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Sscdate',
            field=models.DateField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Unidate',
            field=models.DateField(max_length=10, null=True),
        ),
    ]
