# Generated by Django 3.1.5 on 2021-01-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0010_auto_20210109_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stddetail',
            name='Date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Dateofbirth',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Intdate',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Sscdate',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Testad',
            field=models.CharField(choices=[('G', 'GRE'), ('GM', 'GMAT')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Testad1',
            field=models.CharField(choices=[('G', 'GRE'), ('GM', 'GMAT')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Testeng',
            field=models.CharField(choices=[('I', 'IELTS'), ('T', 'TOEFL')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Testeng1',
            field=models.CharField(choices=[('I', 'IELTS'), ('T', 'TOEFL')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Unidate',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
