# Generated by Django 3.1.5 on 2021-01-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0012_auto_20210109_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stddetail',
            name='SscDoc',
            field=models.ImageField(upload_to='doc'),
        ),
    ]
