# Generated by Django 3.1.5 on 2021-01-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0013_auto_20210109_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Gender',
            field=models.CharField(max_length=50),
        ),
    ]
