# Generated by Django 3.1.5 on 2021-01-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0014_auto_20210110_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Univdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institutemode', models.CharField(max_length=500)),
                ('Institutetype', models.CharField(max_length=500)),
                ('Year', models.CharField(max_length=50, null=True)),
                ('Rank', models.CharField(max_length=50, null=True)),
                ('About', models.CharField(max_length=50, null=True)),
                ('Campuses', models.CharField(max_length=50)),
                ('Departments', models.CharField(max_length=50)),
                ('Education', models.CharField(max_length=50)),
                ('Feeug', models.CharField(max_length=50)),
                ('Feepg', models.CharField(max_length=50)),
                ('Intake', models.CharField(max_length=50)),
                ('Awards', models.CharField(max_length=50)),
                ('Staff', models.CharField(max_length=50)),
                ('Students', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=10, null=True)),
                ('Phonenumber', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=10)),
                ('Applyfee', models.CharField(max_length=50)),
                ('Currency', models.CharField(max_length=50)),
                ('Amount', models.CharField(max_length=50)),
                ('Applyform', models.FileField(upload_to='')),
                ('Duration', models.CharField(max_length=50)),
                ('Applypro1', models.CharField(max_length=50)),
                ('Applypro2', models.CharField(max_length=50)),
                ('Applypro3', models.CharField(max_length=50)),
                ('Applypro4', models.CharField(max_length=50)),
                ('Doc1', models.CharField(max_length=50)),
                ('Doc2', models.CharField(max_length=50)),
                ('Doc3', models.CharField(max_length=50)),
                ('Doc4', models.CharField(max_length=50)),
                ('Doc5', models.CharField(max_length=50)),
                ('Doc6', models.CharField(max_length=50)),
                ('Doc7', models.CharField(max_length=50)),
                ('Doc8', models.CharField(max_length=50)),
                ('Doc9', models.CharField(max_length=50)),
                ('Term1', models.CharField(max_length=500)),
                ('Term2', models.CharField(max_length=500)),
                ('Term3', models.CharField(max_length=500)),
                ('Term4', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Applyingfor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Gender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Intgrading',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Maritial',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Sscgrading',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Testad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Testad1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Testeng',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Testeng1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stddetail',
            name='Unigrading',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
