# Generated by Django 3.1.5 on 2021-01-23 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0016_auto_20210123_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='temp_pass',
        ),
    ]
