# Generated by Django 3.1.4 on 2021-01-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0017_remove_student_temp_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univdetail',
            name='Email',
            field=models.CharField(max_length=50),
        ),
    ]
