# Generated by Django 3.1.5 on 2021-01-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0019_auto_20210126_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newcourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coursename', models.CharField(max_length=50, null=True)),
                ('Coursetype', models.CharField(max_length=50, null=True)),
                ('Facultyname', models.CharField(max_length=50, null=True)),
                ('Courseapproval', models.CharField(max_length=50, null=True)),
                ('Approvalauthority', models.CharField(max_length=50, null=True)),
                ('Tutionfee', models.CharField(max_length=50, null=True)),
                ('Amount1', models.CharField(max_length=50, null=True)),
                ('Sem1', models.CharField(max_length=50, null=True)),
                ('Sem2', models.CharField(max_length=50, null=True)),
                ('Sem3', models.CharField(max_length=50, null=True)),
                ('Sem4', models.CharField(max_length=50, null=True)),
                ('Sem5', models.CharField(max_length=50, null=True)),
                ('Sem6', models.CharField(max_length=50, null=True)),
                ('Duration1', models.CharField(max_length=50, null=True)),
                ('Noofsems', models.CharField(max_length=50, null=True)),
                ('Criteria1', models.CharField(max_length=50, null=True)),
                ('Criteria2', models.CharField(max_length=50, null=True)),
                ('Criteria3', models.CharField(max_length=50, null=True)),
                ('Universitymail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='univdetail',
            name='Amount1',
        ),
        migrations.RemoveField(
            model_name='univdetail',
            name='Approvalauthority',
        ),
        migrations.RemoveField(
            model_name='univdetail',
            name='Courseapproval',
        ),
        migrations.RemoveField(
            model_name='univdetail',
            name='Coursename',
        ),
        migrations.RemoveField(
            model_name='univdetail',
            name='Coursetype',
        ),
        migrations.RemoveField(
            model_name='univdetail',
            name='Criteria1',
        ),
        migrations.RemoveField(
            model_name='univdetail',
            name='Criteria2',
        ),
        migrations.RemoveField(
            model_name='univdetail',
            name='Criteria3',
        ),
        migrations.RemoveField(
            model_name='univdetail',
            name='Duration1',
        ),
        migrations.RemoveField(
            model_name='univdetail',
            name='Facultyname',
        ),
        migrations.RemoveField(
            model_name='univdetail',
            name='Noofsems',
        ),
        migrations.RemoveField(
            model_name='univdetail',
            name='Sem1',
        ),
        migrations.RemoveField(
            model_name='univdetail',
            name='Sem2',
        ),
        migrations.RemoveField(
            model_name='univdetail',
            name='Sem3',
        ),
        migrations.RemoveField(
            model_name='univdetail',
            name='Sem4',
        ),
        migrations.RemoveField(
            model_name='univdetail',
            name='Sem5',
        ),
        migrations.RemoveField(
            model_name='univdetail',
            name='Sem6',
        ),
        migrations.RemoveField(
            model_name='univdetail',
            name='Tutionfee',
        ),
    ]
