# Generated by Django 3.1.4 on 2021-01-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0021_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved',
            name='Mail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
