# Generated by Django 3.1.4 on 2021-01-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0022_saved_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saved',
            old_name='Univeristyname',
            new_name='Univerisityname',
        ),
    ]
