# Generated by Django 3.1.4 on 2021-01-30 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0023_auto_20210130_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saved',
            old_name='Univerisityname',
            new_name='Universityname',
        ),
    ]
