# Generated by Django 3.1.5 on 2021-02-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0024_auto_20210130_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='temp_pass',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='temp_passuni',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
