# Generated by Django 3.1.5 on 2021-02-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0025_auto_20210204_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='temp_pass',
        ),
    ]
