# Generated by Django 3.1.5 on 2021-02-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0026_remove_student_temp_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univdetail',
            name='Currency',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
