# Generated by Django 3.1.5 on 2021-02-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0027_auto_20210217_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univdetail',
            name='Amount',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Applyform',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Applypro1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Applypro2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Applypro3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Applypro4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Awards',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Campuses',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Departments',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Doc1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Doc2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Doc3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Doc4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Doc5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Doc6',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Doc7',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Doc8',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Doc9',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Duration',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Education',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Feepg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Feeug',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Intake',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Phonenumber',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Staff',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Students',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Term1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Term2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Term3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Term4',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
