# Generated by Django 3.1.5 on 2021-02-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0028_auto_20210217_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univdetail',
            name='Institutemode',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Institutetype',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
